### ISSUE TITLE
热点专文：与名人同名

### ISSUE THREAD

**Issue by qzcool** [qzcool/SAC#26]
中信证券：郭富城（国贸营业部），王思聪（营业部借调到总部）

**通过文章吸引公众注意力，从而推广这个项目。**

**Comment by yuyousuoyan** [comment]
Like key words.

**Comment by yuyousuoyan** [comment]
Like key words.

**Comment by qzcool** [comment]
@Reinaaaaa330 这个项目可以开始了，可以在网站找一下名人清单，然后用Excel的VLookup功能实现人名的自动查找。然后把和名人重名的人记录下来，写一篇趣文。

**Comment by qzcool** [comment]
@Reinaaaaa330 Good job, I like your black humor. This issue is now closed.
